# Generated by Django 5.2.8 on 2025-11-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(verbose_name='Уверенность модели')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицировано')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Диагноз',
                'verbose_name_plural': 'Диагнозы',
                'db_table': 'diagnoses',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название болезни')),
                ('description', models.TextField(verbose_name='Описание')),
                ('symptoms', models.TextField(verbose_name='Симптомы')),
            ],
            options={
                'verbose_name': 'Заболевание',
                'verbose_name_plural': 'Заболевания',
                'db_table': 'diseases',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='plants/%Y/%m/%d/', verbose_name='Путь к файлу')),
                ('file_format', models.CharField(max_length=10, verbose_name='Формат')),
                ('camera_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID камеры')),
                ('timestamp', models.DateTimeField(verbose_name='Время съемки')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название препарата/метода')),
                ('description', models.TextField(verbose_name='Описание лечения')),
                ('dosage', models.CharField(max_length=255, verbose_name='Дозировка')),
                ('precautions', models.TextField(verbose_name='Меры предосторожности')),
            ],
            options={
                'verbose_name': 'Метод лечения',
                'verbose_name_plural': 'Методы лечения',
                'db_table': 'treatments',
            },
        ),
    ]
