# Generated by Django 5.2.8 on 2025-11-19 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostics', '0001_initial'),
        ('infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_diagnoses', to=settings.AUTH_USER_MODEL, verbose_name='Кто проверил'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diagnostics.disease', verbose_name='Заболевание'),
        ),
        migrations.AddField(
            model_name='image',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.section', verbose_name='Секция'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='diagnostics.image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='diagnostics.disease', verbose_name='Заболевание'),
        ),
    ]
