# Generated by Django 5.2.8 on 2025-11-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['name'], 'verbose_name': 'Заболевание', 'verbose_name_plural': 'Заболевания'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='heatmap_path',
            field=models.ImageField(blank=True, null=True, upload_to='heatmaps/%Y/%m/%d/', verbose_name='Тепловая карта'),
        ),
        migrations.AlterField(
            model_name='image',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время съемки'),
        ),
    ]
