# Generated by Django 5.2.8 on 2025-11-29 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_alter_disease_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='ml_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ml_diagnoses', to='diagnostics.disease', verbose_name='Изначальный диагноз ML'),
        ),
    ]
