# Generated by Django 5.2.8 on 2025-12-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0004_diagnosis_ml_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='model_accuracy',
            field=models.FloatField(blank=True, help_text='Точность модели на тестовом наборе (в процентах)', null=True, verbose_name='Точность модели'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='model_type',
            field=models.CharField(blank=True, help_text='Тип модели, использованной для диагностики: effnet, custom_cnn, vit, yolo, ensemble', max_length=50, null=True, verbose_name='Тип ML-модели'),
        ),
    ]
