# Generated by Django 5.2.8 on 2025-11-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='Тип действия')),
                ('table_name', models.CharField(max_length=100, verbose_name='Таблица')),
                ('record_id', models.IntegerField(verbose_name='ID записи')),
                ('old_values', models.TextField(blank=True, null=True, verbose_name='Старые значения')),
                ('new_values', models.TextField(blank=True, null=True, verbose_name='Новые значения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
            ],
            options={
                'verbose_name': 'Журнал аудита',
                'verbose_name_plural': 'Журнал аудита',
                'db_table': 'audit_log',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=100, verbose_name='Тип отчета')),
                ('period_start', models.DateTimeField(verbose_name='Начало периода')),
                ('period_end', models.DateTimeField(verbose_name='Конец периода')),
                ('data', models.TextField(verbose_name='Данные отчета')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Сгенерировано')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'db_table': 'reports',
            },
        ),
    ]
