# Generated by Django 5.2.8 on 2025-11-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_plan_text', models.TextField(verbose_name='План лечения')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
                'db_table': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('deadline', models.DateTimeField(verbose_name='Срок исполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'tasks',
            },
        ),
    ]
