# Generated by Django 5.2.8 on 2025-11-19 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostics', '0002_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='agronomist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Агроном'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='diagnostics.diagnosis', verbose_name='Диагноз'),
        ),
        migrations.AddField(
            model_name='task',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='task',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='operations.recommendation', verbose_name='Рекомендация'),
        ),
    ]
